;------------------------------------------------------------------------------
; Filename: mfunc56.mac
; Description: Go to WCS X0Y0
; Notes: Lifts Z to Home First
; Requires: CNC12 V5.06
; Revision Date: 28 JUL 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

;Check to ensure axes are homed
G65 "\cncm\system\check_home_status.cnc"

N100

M25       ;Raise Z to Home
G0 X48 Y0  ;M

N1000